
####
# Apache
apache_vhost:
- { vhost: 'local.mk2.com', docroot: 'mk2/www' }
- { vhost: 'sandbox.local', docroot: 'sandbox' }

####
# mysql
mysql_db:
  - { name: 'mk2' }
  - { name: 'commerce_kickstart' }
