##
# Ansible playbook for setting up a Node.Js development server on Ubuntu 14.04.
#
---
- hosts: all
  user: vagrant
  sudo: yes

  vars_files:
    - vars/settings.yml

  tasks:

    ##
    # Update the box and install common softwares.
    #
    - name: Common | Install 'python-apt' module
      command: apt-get install python-apt -y
      tags: common

    - name: Common | Upgrade all packages
      apt: upgrade=yes update_cache=yes
      tags: common

    - name: Common | Install the locales package
      apt: pkg=locales state=present

    - name: Common | Ensure the locale exists
      command: /usr/sbin/locale-gen {{ locale }}

    - name: Common | Set the locale
      command: /usr/sbin/update-locale LANG={{ locale }} --reset


    ##
    # Installs NTP.
    #
    - name: Common | Install NTP
      apt: pkg={{ item }} state=present
      with_items:
        - ntp
        - ntpdate
      tags: common

    - name: write ntp.conf
      copy: src=templates/ntp.conf dest=/etc/ntp.conf owner=root group=root mode=0644
      tags: common


    ##
    # Apt package installation of common software.
    #
    - name: Common | Install misc utils.
      action: apt pkg={{ item }} state=installed force=yes
      tags: common
      with_items:
        - htop
        - curl
        - python-software-properties
        - python-pycurl
        - software-properties-common
        - unzip
        - vim

    ##
    # Python setup
    #
    - name: Common | Install misc utils.
      action: apt pkg={{ item }} state=installed force=yes
      tags: common
      with_items:
        - python-software-properties
        - python-pycurl
        - python-mysqldb


    ##
    # GIT Setup.
    #
    - name: Git | Install git base packages
      apt: pkg=git-core state=installed force=yes
      tags: common


    ##
    # MySQL database setup.
    #
    - name: General | Install required packages.
      action: apt pkg={{ item }} state=installed force=yes
      tags: common
      with_items:
        - mysql-server
        - mysql-client

    - name: MySQL | Configuration file, my.cnf
      action: template src=templates/mysql-my-cnf.j2 dest=/etc/mysql/my.cnf
      tags: common

    # Secure installation
    - name: MySQL | Set the root password.
      action: mysql_user user=root password={{ mysql_root_password }} host=localhost
      tags: common

    - name: MySQL | Config for easy access as root user
      action: template src=templates/mysql-root-my-cnf.j2 dest=/root/.my.cnf
      tags: common

    - name: MySQL | Remove empty password users
      mysql_user: name='' password='' host=localhost priv=*.*:USAGE state=absent login_user=root login_password={{ mysql_root_password }}
      tags: common

    - name: MySQL | Remove empty password users
      mysql_user: name='' password='' host={{ ansible_fqdn }} priv=*.*:USAGE state=absent login_user=root login_password={{ mysql_root_password }}
      tags: common

    - name: MySQL | Remove the MySQL test database
      mysql_db: db=test state=absent login_user=root login_password={{ mysql_root_password }}
      tags: common


    ##
    # Node.js installation
    #
    - name: Node.js | Package prerequisites for node.js
      action: apt pkg=python-software-properties state=installed
      tags: common

    - name: Node.js | Add the node.js PPA
      action: command add-apt-repository -y ppa:chris-lea/node.js creates=/etc/apt/sources.list.d/chris-lea-node_js-precise.list
      tags: common

    - name: Node.js | Update the apt cache for the new repository
      action: apt update-cache=yes
      tags: common

    - name: Node.js | Install nodejs and npm
      action: apt pkg=nodejs state=installed
      tags: common


    - name: Restart MySQL
      action: service name=mysql state=restarted
      tags: common
